from django.shortcuts import render
import re
import random
from django.http import JsonResponse

def home(request):
    return render(request, 'chatbot_bot/html/index1.html')

def page(request):
    return render(request, 'chatbot_bot/html/page.html')

def input(request,input):
    print(input)
    chatbot_reply=get_response(input)
    print(chatbot_reply)
    return JsonResponse({'reply':chatbot_reply})
    
#imported long_responses.py
R_EATING = "I don't like eating anything because I'm a bot obviously!"

def unknown():
    response = ['<b>Could you please re-phrase that?</b>' ,
                "<b>I am sorry,i'm unaware of this issue,please seek proffesional help</b>",
                'What does that mean?'][random.randrange(4)]
    return response


def messages_probability(user_message, recognised_words, single_response=False, required_words=[]):
    message_certainty = 0
    has_required_words = True

    #Counts how many words are present in each predefined message
    for word in user_message:
        if word in recognised_words:
            message_certainty +=1

     #Calculate the percent of recognised words in a usee message
    percentage = float(message_certainty) / float(len(recognised_words))

    #Checks that the required words are in the string
    for word in required_words:
        if word not in user_message:
            has_required_words = False
            break

    if has_required_words or single_response:
        return int(percentage*100)
    else:
        return 0


def check_all_messages(message):

    highest_probe_list = {}

    def response(bot_response, list_of_words, single_response=False, required_words=[]):
        nonlocal highest_probe_list
        highest_probe_list[bot_response] = messages_probability(message, list_of_words, single_response, required_words)


    #-------------------------------------------------------------------Responses-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    #------------------------------------------------------------------- greet--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    response('Hello! How are you feeling today?',['hello','hi','hey','sup','heya'], single_response=True)
    
    #-------------------------------------------------------------------headache------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    response("What kind of headache do you have :<br>    1. <b>Migraine headache</b> - Pain usually on one side of your head, but often on both sides.<br>     2.<b>Cluster headaches</b> - Cluster headaches include severe pain in or around one eye or on one side of your head they are characterized by severe burning and piercing pain.<br>     3.<b>Tension Headache</b> -  It is pain or discomfort in the head, scalp, or neck, and is often associated with muscle tightness in these areas.<br>     4.<b>Sinus headaches</b> - You may feel pressure around the eyes, cheeks and forehead"
            , ['head','Head','Headache','headache'], single_response=True)

    response('"Migraines" tend to be recurrent, and each attack may last up to 3 days.According to ayurveda if you are having migrane you can eat dairy products or sweets you will surely feel better.<br><b>what else can i help you with?</b>'
            ,['migraine'],single_response=True)
    
    response('Oxygen therapy is one of the main treatments.Getting extra oxygen into your bloodstream can calm your body and help you manage pain.According to ayurveda Camphor, jatasmansi, and sandalwood are also effective. <br><b>what else can i help you with?</b>'
            ,['cluster'],single_response=True)
    
    response('Apply heat to relieve tense neck and shoulder muscles. Use a heating pad set on low, a hot water bottle, a hot shower or bath, a warm compress, or a hot towel. Or apply ice or a cool washcloth to the forehead. Massage also can relieve muscle tension — and sometimes headache pain.According to ayurveda putting lukewarm salt water through Neti Pot in the nostrils may help clear clogged nose and relieve headache too.Apart from that, you can also eat half teaspoons of Sitopaladi powder with honey at least three times a day. <br><b>what else can i help you with?</b>'
            ,['tension'],single_response=True)
    
    response('Boil four glasses of water, add basil leaves, mint leaves, two cloves and a piece of ginger. Let it cool down and keep sipping this throughout the day or you can Grate a piece of ginger and take out its juice. Have this juice with honey two-four times a day. <br><b>what else can i help you with?</b>'
            ,['sinus'],single_response=True)
    
    #-------------------------------------------------------------------stomachache-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    response("What kind of stomachache do you have:<br>  1.<b>Indigestion </b>:A burning sensation or discomfort in the upper abdomen, often after eating feeling full or bloated after eating<br>  2.<b>Gastritis</b>:Gastritis refers to inflammation of the stomach lining. Symptoms include stomach pain, nausea, vomiting, and bloating.<br>   3.<b>Peptic Ulcers</b>: Peptic ulcers are sores that develop in the lining of the stomach or the duodenum (the first part of the small intestine). Symptoms include stomach pain, nausea, vomiting, and bloating.<br> 4.<b>Gastroenteritis</b>: This type of stomach ache is caused by a viral or bacterial infection in the digestive system. Symptoms include stomach pain, diarrhea, vomiting, and fever.<br> 5.<b>Irritable Bowel Syndrome (IBS)</b>: IBS is a common digestive disorder that can cause stomach pain, bloating, constipation, and diarrhea.<br>  6.<b>Food Allergies </b>: Certain foods or ingredients may cause stomach pain, bloating, or diarrhea in people who have allergies or intolerances to them. <br> 7.<b>Inflammatory Bowel Disease (IBD)</b>: IBD is a chronic condition that causes inflammation in the digestive tract. Symptoms include abdominal pain, diarrhea, and rectal bleeding.<br>",['Stomach','Stomachache','stomach','stomachache'], single_response=True)
    
    response('<b>There are several Home remedies that can be used to treat Indigestion at home.Here are some suggestions</b>:<br>1.<b>Ginger</b>: Ginger is a natural digestive aid and can help alleviate indigestion symptoms. You can add fresh ginger to your meals, drink ginger tea, or chew on a piece of ginger root.</br> 2.<b>Turmeric</b>: Turmeric has anti-inflammatory properties and can help reduce inflammation in the digestive system. You can add turmeric powder to your meals or drink turmeric milk.<br> 3.<b>Fennel Seeds</b>: Fennel seeds can help improve digestion and reduce bloating. You can chew on fennel seeds after meals or drink fennel tea.<br><br> <b>what else can i help you with?</b>'
            ,['indigestion','Indigestion'],single_response=True)
   
    response('<b>Here are some Home remedies for gastritis</b>: <br> <b>1.Coconut Water</b>: Coconut water can help soothe the stomach lining and reduce inflammation. Drink coconut water regularly to alleviate gastritis symptoms.<br> <b>2.Aloe Vera</b>: Aloe vera has anti-inflammatory properties and can help soothe the stomach lining. Drink aloe vera juice or take it in supplement form.<br> <b>3.Chamomile Tea</b>: Chamomile tea can help reduce inflammation and alleviate gastritis symptoms. Drink chamomile tea regularly to help soothe the stomach lining.<br><br> <b>what else can i help you with?</b>'
            ,['gastritis','Gastritis'],single_response=True)
   
    response('<b>Here are some Home remedies for peptic ulcer</b>:<br> <b>1.Licorice Root</b>: Licorice root has anti-inflammatory properties and can help reduce inflammation in the stomach lining. It can also help protect the stomach lining from the damaging effects of stomach acid. You can drink licorice root tea or take it in supplement form.<br> <b>2.Amla</b>: Amla, also known as Indian gooseberry, is rich in vitamin C and has anti-inflammatory properties. It can help reduce inflammation and protect the stomach lining from the damaging effects of stomach acid. You can eat fresh amla or take it in supplement form. <br> <b>3.Coconut Water</b>: Coconut water can help soothe the stomach lining and reduce inflammation. Drink coconut water regularly to help alleviate peptic ulcer symptoms.<br> <b>4.Turmeric</b>: Turmeric has anti-inflammatory properties and can help reduce inflammation in the stomach lining. Add turmeric powder to your meals or drink turmeric milk.<br> <b>5.Coriander Seeds</b>: Coriander seeds can help improve digestion and reduce inflammation. You can chew on coriander seeds after meals or drink coriander tea.<br> <b>6.Triphala</b>: Triphala is an Ayurvedic herbal formula that can help improve digestion and reduce inflammation. You can take it in capsule form or mix it with water and drink it.<br><br> <b>what else can i help you with?</b>'
            ,['Peptic','peptic'],single_response=True)
   
    response('<b>Here are some Home remedies for gastroenteritis</b>:<br> <b>1.Ginger</b>: Ginger has anti-inflammatory and antibacterial properties that can help alleviate gastroenteritis symptoms. You can add fresh ginger to your meals, drink ginger tea, or chew on a piece of ginger root.<br> <b>2.Cumin Seeds</b>: Cumin seeds can help improve digestion and reduce inflammation. You can chew on cumin seeds after meals or drink cumin tea.<br><b>Fennel Seeds</b>: Fennel seeds can help alleviate digestive symptoms such as bloating, gas, and abdominal pain. You can chew on fennel seeds after meals or drink fennel tea. <br><b>4.Coconut Water</b>: Coconut water can help replenish electrolytes lost due to diarrhea and vomiting, and can also help soothe the stomach lining. Drink coconut water regularly to help alleviate gastroenteritis symptoms.<br><b>5.Coriander Seeds</b>: Coriander seeds can help improve digestion and reduce inflammation. You can boil coriander seeds in water and drink the resulting tea.<br><b>6.Triphala</b>: Triphala is an Ayurvedic herbal formula that can help improve digestion and reduce inflammation. You can take it in capsule form or mix it with water and drink it.<br><br> <b>what else can i help you with?</b>'
            ,['gastroenteritis','Gastroenteritis'],single_response=True)
   
    response('<b>Here are some Home remedies for Irritable Bowel Syndrome (IBS)</b>:<br> <b>1.Triphala</b>: A combination of three fruits, Triphala is a popular Ayurvedic remedy that is known to improve digestion and relieve constipation. It can be taken in powder form, mixed with water, or as a supplement.<br> <b>2.Licorice</b>: Licorice is known to soothe the digestive tract and reduce inflammation. It can be taken in the form of tea, capsule, or extract.<br><b>2.Aloe Vera</b>: Aloe Vera is known to have a cooling effect on the body and can help relieve inflammation in the digestive tract. It can be taken in the form of juice or gel. <br><b>3.Ginger</b>: Ginger is a natural anti-inflammatory and can help relieve nausea and stomach discomfort. It can be taken in the form of tea or added to food. <br><b>5.Fennel</b>: Fennel seeds are known to relieve gas and bloating and can be taken in the form of tea or added to food.<br><br><b>what else can i help you with?</b>'
            ,['IBS','ibs','irritable','Irritable','Bowel','bowel','Syndrome','syndrome'],single_response=True)
   
    response('<b>Here are some home remedies for mild food allergy symptoms</b>:<br><b>1.Apple Cider Vinegar</b>: Apple cider vinegar has anti-inflammatory properties and can help alleviate itching and swelling. Mix one tablespoon of apple cider vinegar with a glass of water and drink it.<br><b>2.Aloe Vera</b>: Aloe vera has soothing and anti-inflammatory properties and can help alleviate itching and rash. Apply aloe vera gel to the affected area.<br><b>Baking Soda</b>: Baking soda can help reduce itching and swelling. Mix one teaspoon of baking soda with water to form a paste and apply it to the affected area.<br><b>3.Turmeric</b>: Turmeric has anti-inflammatory properties and can help alleviate itching and swelling. Mix turmeric powder with water to form a paste and apply it to the affected area.<br><b>4.Chamomile Tea</b>: Chamomile tea has anti-inflammatory and anti-allergenic properties and can help alleviate itching and swelling. Drink chamomile tea or apply a chamomile tea bag to the affected area.<br><b>5.Honey</b>: Honey has anti-inflammatory and anti-bacterial properties and can help alleviate itching and swelling. Apply honey to the affected area.<br><br> <b>what else can i help you with?</b>'
            ,['Food','Allergies','food','allergies'],single_response=True)
   
    response('<b>Here are some home remedies for Inflammatory Bowel Disease (IBD):</b><br> <b>1.Probiotics</b>: Probiotics are beneficial bacteria that can help improve gut health and reduce inflammation. You can take probiotic supplements or eat foods that are rich in probiotics, such as yogurt, kefir, sauerkraut, and kimchi.<br><b>2.Turmeric</b>: Turmeric has anti-inflammatory properties and can help reduce inflammation in the gut. You can add turmeric to your meals or take it in supplement form.<br><b>2.Fish Oil</b>: Fish oil supplements can help reduce inflammation in the gut and improve symptoms of IBD. You can take fish oil supplements or eat fatty fish, such as salmon, mackerel, and sardines.<br><b>3.Aloe Vera</b>: Aloe vera has anti-inflammatory and healing properties and can help soothe the gut lining. Drink aloe vera juice or take aloe vera supplements.<br><b>4.Exercise</b>: Exercise can help reduce inflammation and improve overall health. Aim for at least 30 minutes of moderate exercise, such as brisk walking or cycling, on most days of the week.<br><b>5.Stress Reduction</b>: Stress can exacerbate IBD symptoms, so it is important to manage stress through relaxation techniques, such as meditation, yoga, or deep breathing exercises.<br><br> <b>what else can i help you with?</b>'
            ,['IBD','ibd','Bowel','bowel'],single_response=True)


    #--------------------------------------------------------------------proresponse---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    response('<b>There are several home remedies that you can try to alleviate pain in the eye</b>: <br><br><b>1.Cold Compress</b>: A cold compress can help reduce eye pain and inflammation. Simply soak a clean cloth in cold water, wring out the excess water, and apply it to your closed eye for 10-15 minutes.<br><b>2.Warm Compress</b>: A warm compress can help relieve eye pain caused by a stye or eyelid infection. Soak a clean cloth in warm water, wring out the excess water, and apply it to your closed eye for 10-15 minutes.<br><b>3.Cucumber</b>: Cucumber slices can help soothe eye pain and reduce inflammation. Simply cut a cucumber into thin slices and place them on your closed eyes for 10-15 minutes.<br><b>4.Rose Water</b>: Rose water can help reduce eye pain and redness. Soak a cotton ball in rose water and place it on your closed eye for 10-15 minutes.<br><b>5.Aloe Vera</b>: Aloe vera has anti-inflammatory properties and can help relieve eye pain. Cut a fresh aloe vera leaf and extract the gel. Apply the gel to your closed eye and leave it on for 10-15 minutes.<br><br><b.If your eye pain persists or worsens, it is important to seek medical attention from an eye doctor.</b><br><br><b>what else can i help you with?</b> '
            ,['eye','eyes','eyesight','sight'],single_response=True)
    
    response('<b>Constant vomiting can be a symptom of several medical conditions, including</b>:<br><br><b>1.Gastrointestinal infections</b>: Viral or bacterial infections in the gastrointestinal tract can cause nausea and vomiting.<br><b>2.Food poisoning</b>: Consuming contaminated food or drink can lead to nausea, vomiting, and other gastrointestinal symptoms.<br><b>3.Migraines</b>: Some people experience vomiting as a symptom of a migraine headache.<br><b>4.Motion sickness</b>: Vomiting can be a symptom of motion sickness, which is caused by a disturbance in the inner ear.<br><b>5.Medications</b>: Certain medications can cause nausea and vomiting as a side effect.<br><b>6.Pregnancy</b>: Morning sickness, which is nausea and vomiting during pregnancy, is a common symptom in the first trimester.<br><b>7.Gallbladder disease</b>: Vomiting can be a symptom of gallbladder disease, which is caused by inflammation or blockage of the gallbladder.<br><b>8.Pancreatitis</b>: Inflammation of the pancreas can cause nausea and vomiting, as well as other gastrointestinal symptoms.<br><br><b>If you are experiencing constant vomiting, it is important to speak with a healthcare professional to determine the underlying cause and receive appropriate treatment</b><br><br><b>what else can i help you with?</b>.'
            ,['Vomiting','vomiting','Vomit','vomit','nauseous','nausea','Nauseous','Nausea','Nauseating','nauseating'],single_response=True)
    
    response('<b>There are several home remedies that you can try to alleviate body pain</b>:<br><b>1.Epsom Salt Bath</b>: Epsom salt contains magnesium, which can help relax your muscles and alleviate pain. Add 2 cups of Epsom salt to a warm bath and soak for 20-30 minutes.<br><b>2.Ginger Tea</b>: Ginger has anti-inflammatory properties that can help reduce body pain. Boil a few slices of fresh ginger in water for 10-15 minutes, strain the tea and add honey to taste.<br><b>3.Turmeric Milk</b>: Turmeric has anti-inflammatory properties that can help reduce body pain. Add 1 teaspoon of turmeric powder to a cup of warm milk and drink before bed.<br><b>4.Massage</b>: Massaging the affected area can help increase blood flow and alleviate pain. Use a massage oil or lotion and gently massage the affected area for a few minutes.<br><b>5.Heat or Cold Compress</b>: A heat or cold compress can help reduce body pain. Apply a hot or cold compress to the affected area for 15-20 minutes.<br><br><b>If your body pain persists or worsens, it is important to seek medical attention from a healthcare professional</b><br><br><b>what else can i help you with?</b>.'
            ,['Body','body'],single_response=True)
    
    response('<b>Dizziness can be caused by several factors such as low blood sugar, dehydration, inner ear problems, or changes in blood pressure. Here are some home remedies that you can try to alleviate dizziness</b>:<br><b>1.Stay Hydrated</b>: Dehydration can cause dizziness, so it is important to stay hydrated. Drink plenty of water throughout the day.<br><b>2.Ginger</b>: Ginger has anti-inflammatory properties that can help reduce dizziness. Boil a few slices of fresh ginger in water for 10-15 minutes, strain the tea and add honey to taste.<br><b>3.Deep Breathing</b>: Deep breathing can help calm the body and alleviate dizziness. Take slow, deep breaths for several minutes.<br><b>4.Acupressure</b>: Applying pressure to certain points on the body can help alleviate dizziness. Try applying pressure to the point located between the two tendons on the inside of the wrist.<br><b>5.Salt</b>: Low blood pressure can cause dizziness, and salt can help raise blood pressure. Try adding a small amount of salt to your diet.<br><br><b>If your dizziness persists or worsens, it is important to seek medical attention from a healthcare professional</b>.<br><br><b>what else can i help you with?</b> '
            ,['Dizzy','dizzy','Dizziness','dizzines'],single_response=True)
    
    response('<b>Fever is a common symptom of many illnesses, and can be caused by viruses, bacteria, or other underlying health conditions. Here are some home remedies that can help alleviate fever:</b><br><b>1.Hydration</b>: Drinking plenty of fluids is important to prevent dehydration, which can worsen fever. Water, herbal teas, and electrolyte-rich drinks can help keep you hydrated.<br><b>2.Rest</b>: Rest is important to help the body fight off infection and reduce fever. Make sure to get plenty of rest and avoid overexerting yourself.<br><b>3.Cool Compress</b>: Applying a cool compress to the forehead, neck, or armpits can help reduce body temperature and alleviate fever.<br><b>4.Herbal Teas</b>: Certain herbal teas, such as ginger, chamomile, or peppermint, can help alleviate fever symptoms.<br><b>5.Garlic</b>: Garlic has antimicrobial properties that can help boost the immune system and fight off infection. You can add garlic to your food or take garlic supplements.<br><b>6.Warm Bath</b>: A warm bath can help reduce fever by promoting sweating and increasing blood flow. Make sure the water is not too hot, as this can worsen fever.<br><br><b>It is important to note that while these home remedies can help alleviate fever symptoms, it is important to seek medical attention if your fever is high, lasts for more than a few days, or is accompanied by other symptoms such as difficulty breathing or chest pain.<br><br> what else can i help you with?</b> '
            ,['Fever','fever','tempreture','Tempreture','shiver','shivering','Shiver','Shivering'],single_response=True)
    
    response('<b>A runny nose can be caused by allergies, a viral infection, or changes in temperature, among other things. Here are some home remedies that can help alleviate a runny nose</b>:<br><br><b>1.Stay Hydrated</b>: Drinking plenty of fluids can help thin out mucus and alleviate a runny nose. Water, herbal teas, and soups can help keep you hydrated.<br><b>2.Use a Saline Solution</b>: Saline nasal sprays or drops can help moisturize and flush out the nasal passages, reducing congestion and runny nose.<br><b>3.Steam Inhalation</b>: Inhaling steam from a bowl of hot water or taking a hot shower can help clear out the nasal passages and reduce congestion.<br><b>4.Ginger</b>: Ginger has anti-inflammatory and antiviral properties that can help alleviate a runny nose. You can add ginger to your food or drink ginger tea.<br><b>5.Honey</b>: Honey has antibacterial and antiviral properties that can help reduce inflammation and alleviate a runny nose. Add honey to your tea or take it by itself.<br><b>6.Turmeric</b>: Turmeric has anti-inflammatory properties that can help reduce inflammation and alleviate a runny nose. Add turmeric to your food or drink turmeric tea.<br><b>7.Essential Oils</b>: Certain essential oils, such as eucalyptus, peppermint, and tea tree oil, can help reduce congestion and alleviate a runny nose. You can add a few drops of essential oil to a bowl of hot water and inhale the steam, or add the oil to a diffuser.<br><br><b>It is important to note that if your runny nose is accompanied by other symptoms, such as fever or cough, or if it persists for more than a few days, it is important to consult a healthcare professional for further evaluation and treatment.</b>'
            ,['runny','Runny','cold','Cold','sneez','Sneez','sneezing','Sneezing'],single_response=True)
    
    response('<b>Here are some home remedies that can help alleviate a cough</b>:<br><br><b>1.Honey and Lemon</b>: Drinking hot water mixed with honey and lemon can help soothe a sore throat and reduce coughing.<br><b>2.Steam Inhalation</b>: Inhaling steam from a bowl of hot water or taking a hot shower can help reduce congestion and alleviate a cough.<br><b>3.Saltwater Gargle</b>: Gargling with warm salt water can help reduce swelling and inflammation in the throat, and alleviate a cough.<br><b>4.Ginger</b>: Ginger has anti-inflammatory properties that can help reduce inflammation and alleviate a cough. You can add ginger to your food or drink ginger tea.<br><b>5.Thyme Tea</b>: Thyme has antispasmodic and expectorant properties that can help reduce coughing and loosen mucus. Drink thyme tea or add thyme to your food.<br><b>6.Licorice Root</b>: Licorice root has demulcent and expectorant properties that can help soothe the throat and reduce coughing. Drink licorice root tea or take licorice root supplements.<br><b>7.Eucalyptus Oil</b>: Eucalyptus oil has anti-inflammatory and decongestant properties that can help reduce coughing and relieve congestion. Add a few drops of eucalyptus oil to a bowl of hot water and inhale the steam, or add the oil to a diffuser.<br><br><b>It is important to note that if your cough persists for more than a few days or is accompanied by other symptoms, such as fever or chest pain, it is important to consult a healthcare professional for further evaluation and treatment.</b>'
            ,['cough','Cough'],single_response=True)
    
    response('<b>There are several home remedies that may help alleviate constipation, including</b>:<br><br><b>1.Drink plenty of water</b>: Drinking enough water helps to soften the stool, making it easier to pass through the colon and out of the body.<br><b>2.Increase fiber intake</b>: Eating a diet rich in fiber can help add bulk to the stool, making it easier to pass. Foods that are high in fiber include fruits, vegetables, whole grains, and legumes.<br><b>3.Exercise regularly</b>: Regular exercise can help stimulate the natural contraction of the intestines, promoting bowel movements.<br><b>4.Use natural laxatives</b>: Certain natural laxatives such as prunes, figs, and flaxseeds can help soften the stool and promote regular bowel movements.<br><b>5.Try probiotics</b>: Probiotics are beneficial bacteria that can help promote a healthy digestive system, which in turn can help alleviate constipation.<br><b>6.Drink warm liquids</b>: Drinking warm liquids, such as herbal tea, can help stimulate the digestive system and promote bowel movements.<br><br><b>It is important to note that if constipation persists or is accompanied by other symptoms such as abdominal pain or bleeding, it is important to seek medical attention.</b>'
            ,['constipation','Constipation'],single_response=True)
    
    response('<b>There are several home remedies that may help alleviate diarrhea, including</b>:<br><br><b>1.Stay hydrated</b>: It is important to drink plenty of fluids to replace the fluids lost during diarrhea. Drinking water, clear broths, and electrolyte-rich fluids such as coconut water or sports drinks can help replenish lost fluids and prevent dehydration.<br><b>2.Follow the BRAT diet</b>: Eating a bland diet consisting of bananas, rice, applesauce, and toast can help alleviate diarrhea. These foods are easy to digest and can help firm up loose stools.<br><b>3.Try probiotics</b>: Probiotics are beneficial bacteria that can help restore the natural balance of gut bacteria and alleviate diarrhea. They can be found in certain foods such as yogurt, kefir, and sauerkraut, or taken as a supplement.<br><b>4.Avoid certain foods</b>: Avoiding spicy, fatty, or high-fiber foods can help reduce irritation to the digestive system and alleviate diarrhea.<br><b>5.Use herbal remedies</b>: Certain herbs such as ginger, chamomile, and peppermint can help soothe the digestive system and alleviate diarrhea.<br><b>6.Rest</b>: Getting enough rest can help reduce stress on the body and promote healing.<br><br><b>It is important to note that if diarrhea persists or is accompanied by other symptoms such as fever or severe abdominal pain, it is important to seek medical attention.</b> '
            ,['diarrhea','Diarrhea','loose','Loose'],single_response=True)
    
    response('<b>There are several home remedies that may help alleviate a sore throat, including</b>:<br><br><b>1.Gargle with salt water</b>: Dissolve 1/2 to 1 teaspoon of salt in a glass of warm water and gargle several times a day. This can help reduce inflammation and loosen mucus.<br><b>2.Drink warm liquids</b>: Drinking warm liquids such as tea or soup can help soothe a sore throat and provide relief.<br><b>3.Use a humidifier</b>: Adding moisture to the air with a humidifier can help alleviate dryness and irritation in the throat.<br><b>4.Honey and lemon</b>: Mix a teaspoon of honey and a squeeze of lemon juice in warm water and drink. Honey has natural antibacterial properties, while lemon contains vitamin C which can help boost the immune system.<br><b>5.Rest your voice</b>: Avoid talking or shouting excessively to allow your throat to rest and heal.<br><b>6.Over-the-counter remedies</b>: Over-the-counter pain relievers such as acetaminophen or ibuprofen can help relieve pain and reduce inflammation.<br><br><b>7.It is important to note that if your sore throat persists for more than a few days, or is accompanied by other symptoms such as fever or difficulty breathing, it is important to seek medical attention.</b>'
            ,['throat','Throat'],single_response=True)
    
    response('<b>There are several home remedies that may help alleviate knee pain</b>:<br><br><b>1.Rest</b>: Resting the knee and avoiding strenuous activity can help reduce pain and inflammation.<br><b>2.Ice therapy</b>: Applying an ice pack to the knee for 15-20 minutes several times a day can help reduce pain and swelling.<br><b>3.Compression</b>: Wearing a compression bandage or sleeve around the knee can help reduce swelling and provide support.<br><b>4.Elevation</b>: Elevating the affected leg can help reduce swelling and improve circulation.<br><b>5.Exercise</b>: Low-impact exercises like cycling, swimming, or walking can help improve knee strength and flexibility, which may help reduce pain.<br><b>6.Turmeric</b>: Turmeric is a natural anti-inflammatory agent that may help reduce knee pain. You can add it to your food or take it as a supplement.<br><b>7.Ginger</b>: Ginger has anti-inflammatory properties and may help reduce knee pain. You can add it to your food or drink ginger tea.<br><b>8.Massage</b>: Massaging the knee can help improve circulation and reduce pain.<br><b>9.Apple cider vinegar</b>: Apple cider vinegar has anti-inflammatory properties and may help reduce knee pain. You can mix it with water and drink it or apply it to the affected area.<br><b>10.Weight loss</b>: If you are overweight, losing weight can help reduce pressure on the knee joint, which may help reduce pain.<br><br><b>what else can i help you with?</b> '
            ,['Knee','knee'],single_response=True)
    
    response('<b>There are several home remedies that can help alleviate itching</b>:<br><br><b>1.Cold compress</b>: Applying a cold compress to the affected area can help reduce itching and inflammation. You can use a washcloth soaked in cold water or wrap an ice pack in a towel.<br><b>2.Oatmeal</b>: Oatmeal is a natural anti-inflammatory agent that can help reduce itching. You can add colloidal oatmeal to your bath or make a paste with oatmeal and water and apply it to the affected area.<br><b>3.Aloe vera</b>: Aloe vera has anti-inflammatory and moisturizing properties that can help reduce itching and soothe the skin. You can apply fresh aloe vera gel to the affected area or use aloe vera lotion.<br><b>4.Coconut oil</b>: Coconut oil has moisturizing properties that can help reduce itching and prevent dry skin. You can apply it directly to the affected area or mix it with essential oils.<br><b>5.Baking soda</b>: Baking soda has alkaline properties that can help reduce itching. You can mix it with water to make a paste and apply it to the affected area.<br><b>6.Tea tree oil</b>: Tea tree oil has anti-inflammatory and antimicrobial properties that can help reduce itching and prevent infection. You can mix it with coconut oil and apply it to the affected area.<br><b>7.Lemon juice</b>: Lemon juice has acidic properties that can help reduce itching and prevent infection. You can apply fresh lemon juice to the affected area or mix it with honey.<br><b>8.Witch hazel</b>: Witch hazel has anti-inflammatory properties that can help reduce itching and swelling. You can apply it to the affected area using a cotton ball.<br><b>9.Chamomile</b>: Chamomile has anti-inflammatory and antioxidant properties that can help reduce itching and promote healing. You can make chamomile tea and apply it to the affected area or use chamomile lotion.<br><b>10.Avoid irritants</b>: Avoiding irritants like harsh soaps, perfumes, and fabrics can help prevent itching and irritation.<br><br><b>what else can i help you with</b> '
            ,['itching','Itching','rashes','rash','Rashes','Rash'],single_response=True)
    
    response('<b>There are several home remedies that may help alleviate ear pain</b>:<br><br><b>1.Apply a warm compress</b>: Placing a warm compress or heating pad against the affected ear can help relieve ear pain. Be sure to use a warm compress, not hot, to avoid burning your skin.<br><b>2.Garlic oil</b>: Garlic has antimicrobial properties and can help reduce ear pain. You can warm garlic oil slightly and use a dropper to apply a few drops to the affected ear.<br><b>3.Saltwater gargle</b>: Gargling with warm salt water can help relieve ear pain by reducing inflammation and drawing out excess fluid. Mix 1 teaspoon of salt in 1 cup of warm water and gargle for a few seconds.<br><b>4.Olive oil</b>: Warm olive oil can help relieve ear pain and reduce inflammation. Use a dropper to apply a few drops of warm olive oil to the affected ear.<br><b>5.Hydrogen peroxide</b>: Hydrogen peroxide can help remove excess earwax, which can cause ear pain. Use a dropper to apply a few drops of hydrogen peroxide to the affected ear, then tilt your head to let the solution drain out.<br><b>6.Onion</b>: Onion has anti-inflammatory properties that can help relieve ear pain. Warm an onion in the oven or microwave, then wrap it in a towel and place it against the affected ear.<br><b>7.Apple cider vinegar</b>: Apple cider vinegar has antibacterial properties and can help relieve ear pain. Mix equal parts apple cider vinegar and water and use a dropper to apply a few drops to the affected ear.<br><b>8.Chewing gum</b>: Chewing gum can help relieve ear pain by equalizing pressure in the ear. This is particularly effective during air travel or when experiencing altitude changes.<br><b>9.Rest</b>: Resting and avoiding activities that may aggravate ear pain can help speed up the healing process.<br><b>10.Over-the-counter pain relievers</b>: Over-the-counter pain relievers such as ibuprofen or acetaminophen can help relieve ear pain. Be sure to follow the recommended dosage and speak to a doctor if the pain persists.<br><br><b>what else can i help you with?</b>'
            ,['ears','Ears','ear','Ear'],single_response=True)
    
    response('<b>If you or someone you know has been stung by a bee, here are some first aid steps to follow</b>:<br><b>1.Remove the stinger</b>: Use a blunt object such as a credit card or fingernail to scrape the stinger out of the skin. Do not use tweezers or squeeze the stinger, as this can release more venom into the skin.<br><b>2.Wash the area</b>: Clean the affected area with soap and water to prevent infection.<br><b>3.Apply a cold compress</b>: Apply a cold compress, such as a cold pack or a washcloth soaked in cold water, to the area to reduce swelling and pain.<br><b>4.Take pain relievers</b>: Over-the-counter pain relievers such as acetaminophen or ibuprofen can help reduce pain and swelling.<br><b>5.Monitor for allergic reactions</b>: If the person has a history of severe allergic reactions to bee stings, or if they develop symptoms such as difficulty breathing, swelling of the face or throat, or a rapid heartbeat, call emergency services immediately.<br><b>6.Seek medical attention</b>: If the bee sting causes a severe reaction, such as a large area of swelling, or if symptoms such as nausea, vomiting, or dizziness develop, seek medical attention immediately.<br><br><b>Remember, most bee stings are not serious and can be treated with these first aid steps. However, if you are unsure about the severity of the reaction or if you develop symptoms such as difficulty breathing, seek medical attention immediately.</b><br><br><b>what else can i help you with ?</b> '
            ,['bee','Bee'],single_response=True)
    
    response('<b>If someone has been bitten by a snake, it is important to seek medical attention as soon as possible. While waiting for medical help, there are some basic first aid steps that can be taken</b>:<br><br>1.Stay calm and keep the person still. This can help slow down the spread of venom through the body.<br>2.Remove any tight clothing or jewelry near the bite site, as this area may swell.<br>3.Keep the affected limb immobilized and lower than the heart, if possible. This can help slow the spread of venom.<br>3.Cover the bite with a clean, dry bandage. Do not apply a tourniquet or restrict blood flow to the area.<br>4.Do not attempt to suck out the venom or cut the bite site, as this can cause further damage.<br>5.Do not apply ice to the bite, as this can cause tissue damage.<br>6.If the person shows signs of shock, such as shallow breathing, rapid heartbeat, or confusion, lay them down with their head slightly lower than their body and cover them with a blanket.<br><br><b>Remember that the best treatment for a snake bite is rapid medical attention. Do not delay seeking professional help by attempting to treat the bite yourself</b>'
            ,['snake','Snake'],single_response=True)
    
    response('please specify your problem '
            ,['sick','well'],single_response=True)


    #--------------------------------------------------------------------srsresponse------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    response('<b>This seems to be a serious issue please seek professional medication as soon as possible.Write "first aid" so that bot can provide you with common first aids. </b>'
            ,[' ','cancer','Cancer','heart','Heart','diabetes','Diabetes','bleeding','Bleeding','Accident','accident','appendix','Appendix','bleed','Bleed'],single_response=True)
    
    #---------------------------------------------------------------------first_aid-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    response("Your problem seems very serious, until you get a professional medical health , here is what you can do for initial care:<br><br><b>1.Bleeding</b>: Apply pressure on the wound with a clean cloth or bandage until the bleeding stops. Elevate the injured area above the heart if possible. Seek medical attention if the bleeding does not stop or if it is a severe wound.<br><b>2.Burns</b>: Run cool (not cold) water over the burn for at least 10 minutes. Cover the burn with a sterile bandage or clean cloth. Do not break any blisters that may have formed. Seek medical attention if the burn is severe or covers a large area.<br><b>3.Choking</b>: If the person is coughing forcefully, encourage them to continue coughing to try to dislodge the object. If the person is unable to cough or speak, give them abdominal thrusts (Heimlich maneuver) to dislodge the object. Call emergency services if the person becomes unconscious.<br><b>4.Fractures</b>: Immobilize the injured area with a splint or support to prevent further injury. Apply ice to the area to reduce swelling and pain. Seek medical attention as soon as possible.<br><b>5.Poisoning</b>: Call poison control immediately if you suspect poisoning. Follow their instructions on how to provide first aid until medical help arrives.<br><b>6.Seizures</b>: Keep the person safe by moving them away from any dangerous objects or situations. Cushion their head and turn them onto their side to prevent choking. Do not restrain them or put anything in their mouth. Call emergency services if the seizure lasts longer than 5 minutes or if it is the person's first seizure.<br><b>7.Shock</b>: Keep the person warm and lying down with their feet elevated. Cover them with a blanket to keep them warm. Call emergency services.<br><br><b>Remember, the goal of first aid is to provide immediate care until professional medical help arrives. Always seek medical attention if you are unsure about the severity of an injury or if the person's condition does not improve </b>"
            ,['firstaid','Firstaid','first','First','aid','Aid'],single_response=True)


    #--------------------------------------------------------------------friendlyresponse------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    response('<b>I am sorry to hear that you are feeling stressed.Stress is a common issue that many people face, and it can have negative effects on both physical and mental health:) <br> Here are some tips that may help you manage your stress:</b><br><br> <b>1.Deep breathing exercises</b>: Take a few deep breaths, inhaling slowly through your nose and exhaling slowly through your mouth. Repeat several times until you feel more relaxed.<br><b>2.Exercise</b>: Physical activity can help reduce stress and improve mood. Try going for a walk, jog, or doing some yoga or stretching exercises.<br><b>3.Mindfulness meditation</b>: This practice involves focusing on the present moment and being aware of your thoughts and feelings without judgment. There are many apps and resources available to guide you through mindfulness meditation.<br><b>Talk to someone</b>: Sometimes talking to a friend, family member, or mental health professional can help you gain perspective and find solutions to your stressors.<br><b>Relaxation techniques</b>: Activities such as taking a warm bath, listening to calming music, or practicing progressive muscle relaxation can help reduce stress.<br><br><b>Remember, it is important to take care of yourself and prioritize your well-being. If your stress levels persist or interfere with your daily life, it may be helpful to seek professional support.</b><br><br><b>what else can i help you with</b>'
            ,['Stress','stress','Stressed','stressed'],single_response=True)
    
    response('<b>I am sorry, I am not authorized to prescribe medications. However, I can tell suggest you home remedies that you can follow to reduce your problem . It is important to talk to your doctor before starting or stopping any medications</b><br><br><b>what else can i help you with</b>'
            ,['medicine','medication','Medicine','Medication'],single_response=True)
    
    response('<b>I am sorry to hear that you are feeling depressed.Here are somethings you can do <br><br></b> 1.Talk to your family and friends.<br> 2.Think about th positive aspects of your life<br> 3.Get enough sleep and encourage in activities that you enjoy <br><br><b>Remember that everyones experience with depression is unique, and what works for one person may not work for another.Work with your mental health professional to develop a treatment plan that is tailored to your needs.<br><br><b>what else can i help you with</b>'
            ,['depressed','Depressed','depression','Depression'],single_response=True)
    
    response("<b>If you're feeling tired, there are several home remedies that can help you feel more energized</b>:<br><br><b>1.Get Enough Sleep</b>: Getting enough sleep is crucial to reducing tiredness. Aim for 7-9 hours of sleep per night, and establish a regular sleep schedule.<br><b>2.Exercise Regularly</b>: Exercise can help improve energy levels by increasing blood flow and releasing endorphins. Aim for 30 minutes of moderate exercise most days of the week.<br><b>3.Stay Hydrated</b>: Dehydration can cause fatigue, so it is important to drink plenty of water throughout the day.<br><b>4.Reduce Stress</b>: Stress can cause fatigue and exhaustion. Practice stress-reducing techniques such as yoga, meditation, or deep breathing.<br><b>5.Eat a Balanced Diet</b>: Eating a balanced diet that includes plenty of fruits, vegetables, whole grains, and lean proteins can help provide the energy your body needs.<br><b>6.Take Breaks</b>: Taking short breaks throughout the day can help reduce tiredness and improve productivity.<br><br><b>It is important to note that if your tiredness persists or if you have fatigue is accompanied by other symptoms such as weakness or dizziness, it is important to consult a healthcare professional for further evaluation and treatment.</b>"
            ,['tired','Tired','fatigue','Fatigue'],single_response=True)
    
    response('Welcome, For proper diagnosis Please consult your nearest Medical Professional.'
            ,['thanks','thankyou'],single_response=True)
    
    response('Happy to know that you are feeling good , Hope you have a nice day!'
            ,['good','Good'],single_response=True)
    
    response('Okay , Hope you have a nice day:))'
            ,['nothing','Nothing'],single_response=True)

    response(R_EATING, ['what','you','eat'], required_words=['you','eat'])

    best_match = max(highest_probe_list, key=highest_probe_list.get)
    # print(highest_probe_list)

    return unknown() if highest_probe_list[best_match] < 1 else best_match

def get_response(user_input):
    split_message = re.split(r'\s+|[,:?!.-]\s*', user_input.lower())
    response = check_all_messages(split_message)
    return response

#Testing the response system
print("Hello I'm a Healthcare BOT. I can give you some home remedies to cure you day to day health care issues.If the problem is serious please seek proffesional medical help ")